---
- name: yum add repos
  yum: name="{{ item }}" state=present
  with_items:
    - https://mirrors.ripple.com/ripple-repo-el7.rpm
- name: yum install
  yum: name="{{ item }}" state=present enablerepo=ripple-stable
  with_items:
    - rippled
