---
- name: yum install 
  yum: name="{{ item }}" state=present
  with_items:
    - openssl
- name: gen key
  script: script.sh
- name: create directory
  file: path=/etc/ssl/private state=directory owner=root group=root mode=0755
- name: copy key
  command: cp /tmp/cert.key /etc/ssl/private/server.key
- name: copy crt
  command: cp /tmp/cert.pem /etc/ssl/certs/server.crt 
